### ISSUE TITLE
Kafka Message Sending Acknowledgement

### ISSUE THREAD

**Issue by fnroid** [spring-projects/spring-integration-kafka#139]
The MessageChannel.send() method is returning true, even if Kafka server(s) does not receive the message, how do we know the kafka server receive the message that producer send by using the The MessageChannel.send()

**Comment by artembilan** [comment]
The `KafkaProducerMessageHandler` has `sync` option:
```
/**
	 * The {@code boolean} indicated if {@link KafkaProducerMessageHandler}
	 * should wait for send operation results or not. Defaults to {@code false}.
	 * In {@code sync} mode a downstream send operation exception will be re-thrown.
	 * @param sync the send mode; async by default.
	 * @since 2.0.1
	 */
	public void setSync(boolean sync) {
		this.sync = sync;
	}
```
In this case the `DirectChannel.send()` will be blocked until successful store in Kafka or an Exception will be thrown.
Otherwise take a look into `errorChannel` for problems.

**Comment by fnroid** [comment]
@artembilan Thanks for your replying, I try writing a demo as what you say, but I can not combine the DirectChannel and KafkaProducerMessageHandler, it sees that this is no relation among them,can you show me a example or demo?

**Comment by artembilan** [comment]
I'm not sure in your problem.
The config copy from our test-case:
````xml
	<int:channel id="inputToKafka" />

	<int-kafka:outbound-channel-adapter id="kafkaOutboundChannelAdapter"
										kafka-template="template"
										auto-startup="false"
										channel="inputToKafka"
										order="3"
										topic="foo"
										message-key-expression="'bar'"
										partition-id-expression="'2'">
		<int-kafka:request-handler-advice-chain>
			<bean class="org.springframework.integration.handler.advice.RequestHandlerCircuitBreakerAdvice" />
		</int-kafka:request-handler-advice-chain>
	</int-kafka:outbound-channel-adapter>

	<int-kafka:outbound-channel-adapter id="kafkaOutboundChannel2"
										kafka-template="template"
										auto-startup="false"
										partition-id="#{0}" />
````

Look at the `inputToKafka` channel definition. It is exactly that `DirectChannel`. So, any sending to it happens on the same thread and if there is some problem with Kafka when `sync = true`, that exception will be re-thrown to you back.

Pay attention to the second adapter definition. Here we don't have `channel` attribute, but use `id`. For convenience Framework creates a `DirectChannel` for you. And uses exactly that `id` to identify bean.

Something similar we have with the JavaConfig, but should say explicitly which class to use for channel bean, e.g.:

````java
@Bean
public MessageChannel inputToKafka() {
      return new DirectChannel();
}

@ServiceActivator(inputChannel = "inputToKafka")
@Bean
public MessageHandler kafkaProducer() {
         KafkaProducerMessageHandler kafkaHandler = new KafkaProducerMessageHandler(this.kafkaTemplate);
        ...
         return kafkaHandler;
}
````

OTOH it would be great to share the code from your side. Although in that case if you still don't understand something.

Thanks for the interest in the project!

**Comment by BornOn911** [comment]
@artembilan 
I want to make sure I understand well about what you said.
1) I wonder wether you mean if I define channel as below, the send() will be a synchronous call and return when it is done
  <int:channel id="inputToKafka" />

    <int-kafka:outbound-channel-adapter 
                                        channel="inputToKafka"
   </int-kafka:outbound-channel-adapter>

   Here I am curious where/when did u call setSync(true) to make it work? I search the code and seems that I didn't find it

2) as you said, for the 2nd adapter definition, it is also a direct channel which I assume it has the same function as the 1st one, then what is the difference between them?

3) in fact, originally, in our project, we are using below through which I can guarantee it worked as synchronous call as well, how does that work on earth?
   ### My colleagues changed the way and use template instead, I want to know how to keep the synchronous behavior.

<int-kafka:outbound-channel-adapter kafka-producer-context-ref="kafkaSyncProducerContext"

</int-kafka:outbound-channel-adapter>

<int-kafka:producer-context id="kafkaSyncProducerContext" producer-properties="producerProperties">
  <int-kafka:producer-configurations>
     <int-kafka:producer-configuration async="false" />
 </int-kafka:producer-configurations>
</int-kafka:producer-context>

**Comment by garyrussell** [comment]
Sync is not currently available using XML configuration (it was added after the 2.0.0 release and we generally don't change XML schemas in point releases); it will be add in the upcoming 2.1 release, which is expected next week.

In the meantime, you can set the flag by giving the adapter an id (e.g. `kafkaOut`, then get a reference to it (by autowiring or `context.getBean()`...

```java
@Autowired
@Qualifier("kafkaOut.handler")
private KafkaProducerMessageHandler<?, ?> handler;

...

    handler.setSync(true);
```

Or use `@Bean` java configuration for the adapter instead of XML.

**Comment by Franksha** [comment]
@garyrussell 

we don't use any code here so seems that I have to wait for the upcoming 2.1 release.
good thing is it will come within 1 week so that I don't need to wait too long.

just want to confirm that it will be an attribute inside "int-kafka:outbound-channel-adapter",
is that correct?

**Comment by garyrussell** [comment]
Yes; I just created the [pull request](https://github.com/spring-projects/spring-integration-kafka/pull/144). It should be in a a 2.1.0.BUILD-SNAPSHOT some time today if you want to watch that PR.

**Comment by Franksha** [comment]
@garyrussell 

Thanks,lt me keep an eye on it and the upcoming 2.1 release

**Comment by artembilan** [comment]
@Franksha ,

Thank you for pointing that out!
The issue has been just fixed and merged to master.

Indeed, we are going to release `2.1.0.RELEASE` the next Monday together with the Spring Kafka 1.1.0.RELEASE. 
Meanwhile you can bypass the custom namespace support and just configure `KafkaProducerMessageHandler` as a regular bean. Fortunately, since version `2.0`  it is straightforward:
````xml
<int:outbound-channel-adapter id="kafkaOutboundChannel">
	<bean class="org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler">
		<constructor-arg ref="template"/>
		<property name="topicExpression">
			<bean class="org.springframework.expression.common.LiteralExpression">
				<constructor-arg value="foo"/>
			</bean>
		</property>
		<property name="messageKeyExpression">
			<bean class="org.springframework.expression.common.LiteralExpression">
				<constructor-arg value="bar"/>
			</bean>
		</property>
		<property name="sync" value="false"/>
	</bean>
</int:outbound-channel-adapter>
````

Let us know and will close the issue as fixed!

**Comment by Franksha** [comment]
@artembilan 
thanks.

**Comment by artembilan** [comment]
Closed with the fix in the #144

**Comment by Franksha** [comment]
@artembilan  @garyrussell 
 I performed change as below, but it still can't give me the expect result, do you have idea what happen there or do you have a real end to end test to confirm the synchronous call works?
### My test method is below and it works well for spring kafka integration 1.1
1) launch everything
2) launch consumer command
3) post message to our endpoint for 100 times by our endPoint
4) make sure message can be written to topic
5) kill kafka process
6) error happen for consumer 
7) our endPoint return error with exception( for spring integration kafka, it was failed to *** for 5 times)

-        <spring.integration.kafka.version>2.0.1.RELEASE</spring.integration.kafka.version>
 +        <spring.integration.kafka.version>2.1.0.RELEASE</spring.integration.kafka.version>

     <int-kafka:outbound-channel-adapter id="kafkaOutboundChannelAdapterSync"
                                          kafka-template="template"
                                          auto-startup="true"
 +                                        sync="true"
                                          channel="kafkaSyncOutboundChannel"
                                          topic-expression="headers.topic"
                                          message-key-expression="headers.messageKey">

**Comment by artembilan** [comment]
Ok. Show, please, your test method. I mean code, not description.

**Comment by artembilan** [comment]
Here you can find our test-case, but it is based on mock. Just to be sure that our config is correct: https://github.com/spring-projects/spring-integration-kafka/blob/master/src/test/java/org/springframework/integration/kafka/config/xml/KafkaOutboundAdapterParserTests.java

**Comment by Franksha** [comment]
It is hard to show everything.
we have an integration environment which include
endPoint/kafka broker/zookeeper/kafka consumer.

I will build docker for our endpoint at first and them launch everything with the integration environment.

From client, I will send below message:
curl -X POST -H 'Content-type: application/json' -d '{"providerId" : "111", "serviceId": "222","name":"TestAlert","active":true, "description":"=============","trigger" : "", "timeout": 100,"severity":1,"server":"fe2-monitor1-2-tyo","classname":"SoftwareService","source":"Nagios","timestamp":1, "deliveryServices" : "dService"}' 'http://localhost:8080/funnel/v1/publishAlert'

then I just do "docker exec -i kafka /bin/sh"
then use consumer command to monitor the know topic and find kafka process and kill it

**Comment by Franksha** [comment]
I just update spring kafka integration version , do I need to upgrade version of spring and spring integration, now I am using 4.2.5.RELEASE for them

**Comment by artembilan** [comment]
Right, it's very difficult to reproduce. So, I recommend you to come up with short code to figure out what you have missed.
I'll write some test for you tomorrow, but that will be with embedded Kafka.
Out of topic. Note why you need Zookeeper. Kafka 0.10 client is free already of that extra complexity.

**Comment by artembilan** [comment]
The Spring Integration Kafka 2.1 is enough for upgrade. Be sure that your Broker is of version `0.10`

**Comment by artembilan** [comment]
Hm. SIK Version `2.1` Is based on SI 4.3.2. So, that isn't going to work with 4.2.5

**Comment by artembilan** [comment]
@Franksha , one more time: where is your problem?

If I use `sync = true` and stop the Kafka broker, I have this exception:
```
org.springframework.integration.MessageTimeoutException: Timeout waiting for response from KafkaProducer; nested exception is java.util.concurrent.TimeoutException

	at org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.handleMessageInternal(KafkaProducerMessageHandler.java:160)
```

Maybe your problem is upstream where you use some async `MessageChannel` - `ExecutorChannel`, `QueueChannel`? Or your flow starts with the `Poller`.

**Comment by Franksha** [comment]
@artembilan 
I assume that when broker is stopped, send() should throw exception to me so that caller will know that send() failed.
BTW,yesterday I do saw 2 timeout response from my endPoint while most of the others are succeed.
(I just send the same message for 100 times)

**Comment by artembilan** [comment]
We throw an exception there and it is `Timeout waiting for response from KafkaProducer;`.

What do you mean? What do you expect from there else?

The `KafkaProducer` collects requests and perform real send asynchronously in the internal loop anyway returning to us a `Future<?>`. and already here we fail waiting for the value there. 

Your use-case is just unclear. Not sure how to help you.

Show the code (or config), please, and point us what you expect here and there.
As I said before, the simple Spring Boot application would be great to play.

I don't provide you any tests as I promised, because after the night I don't see any obstacles. Anyway, here is what we have:
````java
@Test
	public void testSyncMode() {
		@SuppressWarnings("resource")
		MockProducer<Integer, String> mockProducer =
				new MockProducer<>(false, new IntegerSerializer(), new StringSerializer());
		KafkaTemplate<Integer, String> template = new KafkaTemplate<>(() -> mockProducer);
		KafkaProducerMessageHandler<Integer, String> handler = new KafkaProducerMessageHandler<>(template);
		handler.setBeanFactory(mock(BeanFactory.class));
		handler.afterPropertiesSet();

		handler.setSync(true);
		handler.setTopicExpression(new LiteralExpression("foo"));

		Executors.newSingleThreadExecutor()
				.submit(() -> {
					RuntimeException exception = new RuntimeException("Async Producer Mock exception");
					while (!mockProducer.errorNext(exception)) {
						Thread.sleep(100);
					}
					return null;
				});

		assertThatExceptionOfType(MessageHandlingException.class)
				.isThrownBy(() -> handler.handleMessage(new GenericMessage<>("foo")))
				.withMessageContaining("Async Producer Mock exception")
				.withCauseExactlyInstanceOf(ExecutionException.class)
				.withRootCauseExactlyInstanceOf(RuntimeException.class);

		handler.setSendTimeout(1);

		assertThatExceptionOfType(MessageTimeoutException.class)
				.isThrownBy(() -> handler.handleMessage(new GenericMessage<>("foo")))
				.withMessageContaining("Timeout waiting for response from KafkaProducer")
				.withCauseExactlyInstanceOf(TimeoutException.class);
	}
````
We configure `KafkaTemplate` for the `MockProducer`, use `handler.setSync(true);`, perform `mockProducer.errorNext(exception)` for the `send` and assert that we catch an exception from the `KafkaProducerMessageHandler` directly on the `handleMessage()`.

**Comment by Franksha** [comment]
from below code, since I can see related exceptions in my log, so synchronous should already happen, but seems my code didn't get it from replyChannel now...
		if (this.sync) {
			if (this.sendTimeout < 0) {
				future.get();
			}
			else {
				try {
					future.get(this.sendTimeout, TimeUnit.MILLISECONDS);
				}
				catch (TimeoutException te) {
					throw new MessageTimeoutException(message, "Timeout waiting for response from KafkaProducer", te);
				}
			}
		}




Sep 21, 2016 2:09:16 PM org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel send
WARNING: Reply message received but the receiving thread has exited due to a timeout:ErrorMessage [payload=org.springframework.integration.MessageTimeoutException: Timeout waiting for response from KafkaProducer; nested exception is java.util.concurrent.TimeoutException, headers={id=04863177-4b00-a96b-13ae-cc627810ac37, timestamp=1474481356030}]

Sep 21, 2016 2:09:17 PM org.springframework.integration.handler.LoggingHandler handleMessageInternal
SEVERE: org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler#1]; nested exception is java.util.concurrent.ExecutionException: org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.TimeoutException: Batch Expired
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:139)
	at org.springframework.integration.endpoint.PollingConsumer.handleMessage(PollingConsumer.java:129)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:272)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.access$000(AbstractPollingEndpoint.java:58)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:190)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$1.call(AbstractPollingEndpoint.java:186)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller$1.run(AbstractPollingEndpoint.java:353)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor$1.run(ErrorHandlingTaskExecutor.java:55)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.TimeoutException: Batch Expired
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at org.springframework.util.concurrent.SettableListenableFuture.get(SettableListenableFuture.java:138)
	at org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.handleMessageInternal(KafkaProducerMessageHandler.java:157)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:127)
	... 10 more
Caused by: org.springframework.kafka.core.KafkaProducerException: Failed to send; nested exception is org.apache.kafka.common.errors.TimeoutException: Batch Expired
	at org.springframework.kafka.core.KafkaTemplate$1.onCompletion(KafkaTemplate.java:226)
	at org.apache.kafka.clients.producer.internals.RecordBatch.done(RecordBatch.java:99)
	at org.apache.kafka.clients.producer.internals.RecordBatch.maybeExpire(RecordBatch.java:136)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.abortExpiredBatches(RecordAccumulator.java:220)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:128)
	... 1 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Batch Expired

**Comment by Franksha** [comment]
do you have idea what is the this.sendTimeout by default? I should haven't set it
for our gateway, default-reply-timeout is 5000

**Comment by artembilan** [comment]
Well, at least according `sync` we are already on the same page.

Now about the `replyChannel`.
You have this WARN:
```
Sep 21, 2016 2:09:16 PM org.springframework.messaging.core.GenericMessagingTemplate$TemporaryReplyChannel send
WARNING: Reply message received but the receiving thread has exited due to a timeout:ErrorMessage [payload=org.springframework.integration.MessageTimeoutException: Timeout waiting for response from KafkaProducer; nested exception is java.util.concurrent.TimeoutException, headers={id=04863177-4b00-a96b-13ae-cc627810ac37, timestamp=1474481356030}]
```
So, need to understand what you do with the `<gateway>` there and how you expect reply.
Right now you end up with the timeout on the waiting for reply, therefore any late replies are finished with that message in logs.

Please, explain your use-case. What that `<gateway>`  do there?
Although it would be better to move that discussion already to StackOverflow. That problem isn't for the `sync` feature in Spring Integration Kafka.

Thanks for your patience.

**Comment by arunbalan** [comment]
What are my options, if I can't upgrade to kafka 0.10+? I am stuck with kafka 0.9 and can't upgrade. Is there any way I can still set the sync to true? I need to report an error when the message send was unsuccessful. 

(I am using spring-integration-kafka - 1.3.1.RELEASE)

**Comment by garyrussell** [comment]
?? spring-integration-kafka 1.3.1 uses the 0.8.2.2 client.

spring-integration-kafka 2.0.1  uses spring-kafka 1.0.6 which uses the 0.9.0.1 client.

**Comment by artembilan** [comment]
If you are with Kafka 0.9, you should already use Spring Integration Kafka 2.0. Exactly this one is based on Spring Kafka 1.0 which is aimed for Kafka 0.9. And there is really already `sync` option on the `KafkaProducerMessageHandler`.

**Comment by arunbalan** [comment]
hi Gary, thanks for your quick response. That is right, I forgot to mention that my application also connects to another kafka cluster which is running 0.8. I cant avoid this either, as it is required for our logging infrastructure (ELK)

**Comment by artembilan** [comment]
@arunbalan,

Please, consider to move your question to community forum. Looks like your problem isn't related to this issue. More over it is closed already.

Thanks
